package jxtemplate.project.bundle.lib.src

/**
 * Created by liuheng on 2021/6/3.
 * DemoClass
 */

fun DemoClassKt(
        bundle: String
) = """
package com.jd.pingou.${bundle};

import android.content.Context;
import android.content.Intent;
import android.os.Bundle;
import android.os.Parcel;
import android.os.Parcelable;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

/**
 * Created by song on 16-3-24.
 */
public class DemoClass {

    /**
     * TODO: Refer to http://stackoverflow.com/questions/3323074/android-difference-between-parcelable-and-serializable
     */

    /**
     * TODO: Suggested for Intent parameters.
     *
     * It can be generated by Android Parcelable Code Generator automatically.
     */
    public static class DemoParcelableClass implements Parcelable {

        public String name = "It's a demo for parcelable generator";

        public static class Description {
            public String content;
        }

        /**
         * TODO: CONFIRMATION!!!
         *
         * There was a bug in version 0.6.2 and older. It shouldn't use
         * "List.class.getClassLoader()". You're able to update the plugin
         * or modify them manually.
         */
        public List<Description> descriptionsList;

        /**
         * TODO: Customized parameterized classes
         *
         * A customized parameterized classes is NOT directly supported by
         * the Generator. You should use its actual types for input and
         * output.
         */
        class DemoParameterizableClass<X, Y> {
            public X x;
            public Y y;
        }

        public DemoParameterizableClass<String, Integer> params;

        @Override
        public int describeContents() {
            return 0;
        }

        @Override
        public void writeToParcel(Parcel dest, int flags) {
            dest.writeString(this.name);
            dest.writeList(this.descriptionsList);

            // TODO: Failed !!!
            // TODO: dest.writeParcelable(this.params, flags);

            // TODO: Correct.
            dest.writeString(this.params.x);
            dest.writeInt(this.params.y);
        }

        public DemoParcelableClass() {
        }

        protected DemoParcelableClass(Parcel in) {
            this.name = in.readString();
            this.descriptionsList = new ArrayList<Description>();

            // TODO: WRONG!!! Please confirm the similar lines do NOT exist !!!
            // TODO: in.readList(this.descriptionsList, List.class.getClassLoader());

            // TODO: Correct.
            in.readList(this.descriptionsList, Description.class.getClassLoader());

            // TODO: FAILED !!!
            // TODO: this.params = in.readParcelable(DemoParameterizableClass<String, Integer>.class.getClassLoader());

            // TODO: Correct.
            this.params = new DemoParameterizableClass<>();
            this.params.x = in.readString();
            this.params.y = in.readInt();
        }

        public static final Parcelable.Creator<DemoParcelableClass> CREATOR = new Parcelable.Creator<DemoParcelableClass>() {
            @Override
            public DemoParcelableClass createFromParcel(Parcel source) {
                return new DemoParcelableClass(source);
            }

            @Override
            public DemoParcelableClass[] newArray(int size) {
                return new DemoParcelableClass[size];
            }
        };
    }

    /**
     * TODO: Suggested. Using Parcelable for object transferring.
     */
    public static void startActivityWithPacelableObject(Context context) {
        DemoParcelableClass demo = new DemoParcelableClass();
        Intent intent = new Intent(context, DemoMainActivity.class);
        Bundle bundle = new Bundle();
        bundle.putParcelable("DEMO_PARAM", demo);
        intent.putExtras(bundle);

        context.startActivity(intent);
    }

    /**
     * TODO: WRONG!!! DO NOT USE FOR Intent !!!
     */
    public static class DemoSerializableClass implements Serializable {
        public String description = "It's a demo for serializable generator";
    }

    /**
     * TODO: WRONG !!! Using Serializable for object transferring.
     */
    public static void startActivityWithSerializableObject(Context context) {
        Intent intent = new Intent(context, DemoMainActivity.class);
        Bundle bundle = new Bundle();
        DemoSerializableClass demo = new DemoSerializableClass();
        bundle.putSerializable("DEMO_PARAM", demo);
        intent.putExtras(bundle);

        context.startActivity(intent);
    }

}

""".trimIndent()